menusite/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('register/',views.register_view,name='register'),
]

menusite/menusite/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('articles.urls')),
    path('accounts/',include('accounts.urls')),
    path('pantry/recipes/',include('recipes.urls'),)
    # path('pantry/',include('receipe.urls')),
]

menusite/recipes/urls.py
# here we go for different view for the routes
from django.urls import path
from .views import recipe_create_view,recipe_detail_view,recipe_list_view,recipe_update_view,recipe_detail_hx_view


# declaring the app name
app_name = 'recipes'


urlpatterns = [
    path('',recipe_list_view,name='list'),
    path('create/',recipe_create_view,name='create'),
    path('hx/<int:id>/',recipe_detail_hx_view,name='hx-detail'),
    path('<int:id>/edit/',recipe_update_view,name='update'),
    path('<int:id>/',recipe_detail_view,name='detail'),
]

menusite/accounts/models.py
from django.db import models

# Create your models here.

menusite/accounts/views.py
from django.shortcuts import render , redirect
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm

# Create your views here.



# user registration form
def register_view(request):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        user_obj = form.save()
        return redirect('accounts:login')
    return render(
        request,
        'accounts/register.html',
        {
            'form':form
        }
    )


#  user login view
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request,data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect('articles:list_article')
    else:
        form = AuthenticationForm(request)
        
    return  render(request,
                       'accounts/login.html',
                       {
                        
                       })
    
    
    

#  user logout view for the user
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:login')
        
    return render(request,
                  'accounts/logout.html',{})

menusite/templates/accounts/login.html
{% extends "base.html" %}


{% block title %}
 login
{% endblock title %}


{% block content %}
  {% if not request.user.is_authenticated %}
     <p>If are new user then <a href="{% url 'accounts:register' %}">register</a>here</p>
   <div style="margin-top:30px">
     <form method="POST">
        {% csrf_token %}
        {% if error %}
           <p style="color:red"> {{ error }} </p>
        {% endif %}
        
        <div>
            <input type="text" name="username" placeholder="username">
        </div>
        <div>
            <input type="password" name="password" placeholder="password">
        </div>
        <div>
            <input type="submit" value="login">
        </div>
     </form>
   </div>

  {% else %}
  <p>hey you are already logged in are you want to <a href="{% url 'accounts:logout' %}">logged</a> out.</p>
  
  {% endif %}
{% endblock content %}

menusite/templates/accounts/logout.html
{% extends "base.html" %}

{% block title %}
  Logout
{% endblock title %}  


{% block content %}
  {% if request.user.is_authenticated %}
      <div style="margin-top:30px">
         <form method="POST">
            {% csrf_token %}
             <div>
                <p>Are you sure want to logout!!</p>
                <input type="submit" value="Yes">
             </div>
         </form>
      </div>
  {% else %}
     <p>You are not logged in want to <a href="{% url 'accounts:login' %}">login</a>?</p>
  {% endif %}
{% endblock content %}

menusite/templates/accounts/register.html
{% extends "base.html" %}


{% block title %}
Register
{% endblock title %}



{% block content %}
   {% if not request.user.is_authenticated %}
        <div style="margin-top:30px">
            <form method="POST" action="">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <input type="submit" value="register">
                </div>
            </form>
        </div>
   {% else %}
   <p>
      you already have an account to access please <a href="{% url "accounts:login" %}">login</a>
   </p>
   {% endif %}
{% endblock content %}