menusite/menusite/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('articles.urls')),
    path('accounts/',include('accounts.urls')),
    path('pantry/recipes/',include('recipes.urls'),)
    # path('pantry/',include('receipe.urls')),
]

menusite/recipes/urls.py
# here we go for different view for the routes
from django.urls import path
from .views import recipe_create_view,recipe_detail_view,recipe_list_view,recipe_update_view,recipe_detail_hx_view


# declaring the app name
app_name = 'recipes'


urlpatterns = [
    path('',recipe_list_view,name='list'),
    path('create/',recipe_create_view,name='create'),
    path('hx/<int:id>/',recipe_detail_hx_view,name='hx-detail'),
    path('<int:id>/edit/',recipe_update_view,name='update'),
    path('<int:id>/',recipe_detail_view,name='detail'),
]

menusite/recipes/models.py
from django.db import models
import pint
from django.conf import settings
from django.urls import reverse
from .validators import validate_unit_of_measurement
from .utils import number_str_to_float


# Create your models here.

# here we go for the model recipe which will be one to many relationship with its ingredients
class Recipe(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description  = models.TextField(blank=True,null=True)
    directions = models.TextField(blank=True,null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    # absolute url
    def get_absolute_url(self):
        return reverse('recipes:detail',kwargs={"id" : self.id})
    
    # edit url
    def get_edit_url(self):
        return reverse('recipes:update',kwargs={"id" : self.id})
    
    # edit hx url
    def get_hx_url(self):
        return reverse('recipes:hx-detail', kwargs={"id": self.id})
    
    # get ingredients
    def get_ingredients(self):
        return self.recipeingredient_set.all()
    
# model for the recipe ingredient for the recipe 
class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True,null=True)
    quantity = models.CharField(max_length=50)
    quantity_as_float = models.FloatField(blank=True,null=True)
    unit = models.CharField(max_length=50,validators=[validate_unit_of_measurement])
    directions = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    
    def get_absolute_url(self):
        return self.recipe.get_absolute_url()
    
    
    # here we create utility conversion for unit using the pint
    def convert_to_system(self,system='mks'):
        if self.quantity_as_float is None:
            return None
        ureg = pint.UnitRegistry(system=system)
        measurements = self.quantity_as_float * ureg[self.unit]
        return measurements
    
    def  as_mks(self):
        # same as mks
        measurements = self.convert_to_system(system='mks')
        return measurements.to_base_units()
    
    def as_imperial(self):
        # for imperial system
        measurements = self.convert_to_system(system='imperial')
        return measurements.to_base_units()
    
    def to_ounces(self):
        m = self.convert_to_system()
        return m.to('ounces')
    
    
    # over-riding the save method for the float quantity
    def save(self,*args,**kwargs):
        qty = self.quantity
        qty_as_float , qty_as_float_success = number_str_to_float(qty)
        if qty_as_float_success:
            self.quantity_as_float = qty_as_float
        super().save(*args,**kwargs)
    
    

menusite/recipes/forms.py
# creating the new recipe form for the user
from django import forms
from .models import Recipe , RecipeIngredient


# creating the form
class RecipeForm(forms.ModelForm):
    error_css_class = 'error-field'
    required_css_class = 'required-css'
    name = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder" : "recipe name"
    }))
    class Meta:
        model = Recipe
        fields = ['name','description','directions']
        
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        # self.fields['name'].widget.attrs.update({'class':'form-control-2'})
        
        for field in self.fields:
            new_data = {
                'placeholder': f'Recipe {str(field)}',
                'class': 'form-controll'
            }
            self.fields[str(field)].widget.attrs.update(new_data)
        
        
# creating the form for the ingredients
class RecipeIngredientForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredient
        fields = ['name','quantity','unit']

menusite/recipes/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from django.contrib.auth.decorators import login_required
from django.forms import modelformset_factory
from django.http import HttpResponse , Http404
from django.urls import reverse
from .forms import RecipeForm , RecipeIngredientForm
from .models import Recipe , RecipeIngredient

# Create your views here.

# creating the crud operation for the recipe

@login_required
def recipe_list_view(request):
    qs = Recipe.objects.filter(user=request.user)
    context = {
        'object_list' : qs
    }
    return render(request,
                  'recipes/list.html',
                  context=context)

@login_required
def recipe_detail_view(request,id=None):
    # qs = Recipe.objects.filter(id=id).first()
    # object = get_object_or_404(Recipe,id=id,user=request.user)
    hx_url = reverse("recipes:hx-detail",kwargs={'id':id})
    context = {
        'hx_url': hx_url
    }
    return render(
        request,
        'recipes/detail.html',
        context=context
    )
    
    
# for the detail view for the html view
@login_required
def recipe_detail_hx_view(request,id=None):
    # qs = Recipe.objects.filter(id=id).first()
    if not request.htmx:
        raise Http404
    try:
        object = Recipe.objects.get(id=id,user=request.user)
    except:
        object = None
        
    # if it is returning nothing
    if object is None:
        return HttpResponse('Not found')
    context = {
        'object' : object
    }
    return render(
        request,
        'recipes/partials/detail.html',
        context=context
    )

# recipe create view
@login_required
def recipe_create_view(request):
    form = RecipeForm(request.POST or None)
    context = {
        'form' : form
    }
    # check form is valid or not
    if form.is_valid():
        # if true then save in an object 
        obj = form.save(commit=False)
        # saving the user
        obj.user = request.user
        # then save the data
        obj.save()
        return redirect(obj.get_absolute_url())
    return render(
        request,
        'recipes/create-update.html',
        context=context
    )


# update view
@login_required
def recipe_update_view(request,id=None):
    obj = get_object_or_404(Recipe,id=id,user=request.user)
    form = RecipeForm(request.POST or None, instance=obj)
    # form_2 = RecipeIngredientForm(request.POST or None)
    # FormSet = modelformset_factory()
    RecipeIngredientFormSet = modelformset_factory(RecipeIngredient,form=RecipeIngredientForm,extra=0)
    qs = obj.recipeingredient_set.all()
    formset = RecipeIngredientFormSet(request.POST or None, queryset=qs)
    context = {
        'form' : form,
        'formset' : formset,
        'obj'  : obj
    }
    # check form is valid or not
    if all([form.is_valid(),formset.is_valid()]):
        # if true then save in an object
        # this is two different form but they are connected through a foreign key
        # so have to save this way
        parent = form.save(commit=False)
        parent.save()
        for form in formset:
            child = form.save(commit=False)
            child.recipe = parent
            child.save()
        context['message'] = 'data saved...'
    
    # checking the valid htmx
    
    if request.htmx:
        return render(request,"recipes/partials/forms.html",context)
        
    return render(
        request,
        'recipes/create-update.html',
        context=context
    )
    

menusite/recipes/templates/recipes/create-update.html
{% extends "base.html" %}

{% block title %}
Create Recipe
{% endblock title %}


{% block content %}
 <style>
   .ingredients-form {
     border-bottom : 1px solid black;
   }

   .hidden{
     display: none;
   }
 </style>
  {% comment %} check for update or not {% endcomment %}

    <div style="margin-top:30px">
        {% include "recipes/partials/forms.html" %}
    </div>
 

  <script>
    
    const addMoreBtn = document.getElementById('add-more');
    const totalNewForm = document.getElementById('id_form-TOTAL_FORMS');
   

    addMoreBtn.addEventListener('click', add_new_form);

    function add_new_form(event){
      if(event){
        event.preventDefault();
      }
      const currentIngredientsForm = document.getElementsByClassName('ingredients-form');
      //add more element to the html form
      let currentFormCount = currentIngredientsForm.length ;
      const copyEmptyFormEl = document.getElementById('empty-form').cloneNode(true);
      const formCopyTarget = document.getElementById('ingredient-form-List');
      copyEmptyFormEl.setAttribute('class','ingredients-form');
      copyEmptyFormEl.setAttribute('id', `form-${currentFormCount}`);
      const regex = new RegExp('__prefix__','g');
      copyEmptyFormEl.innerHTML = copyEmptyFormEl.innerHTML.replace(regex,currentFormCount)
      // append the duplicate
      totalNewForm.setAttribute('value',currentFormCount + 1);
      formCopyTarget.append(copyEmptyFormEl);
    }



  </script>
{% endblock content %}

menusite/recipes/templates/recipes/detail.html
{% extends "base.html" %}

{% block title %}
  {{ object.name }}
{% endblock title %}


{% block content %}
  
  <div hx-get='{{ hx_url }}' hx-trigger='revealed'>
     <div class="htmx-indicator">Loading ...</div>
  </div>

{% endblock content %}

menusite/recipes/templates/recipes/list.html
{% extends "base.html" %}


{% block title %}
Recipe List
{% endblock title %}

{% block content %}
  <h1>My Recipes</h1>
  <a href="{% url 'recipes:create' %}">Create Recipe</a>
  <ul>
      {% for object in object_list %}
        {% if object.name %}
           <li><a href='{{ object.get_absolute_url }}'>{{ object.name}}</a></li>
        {% endif %}
      {% endfor %}
  </ul>
{% endblock content %}