menusite/articles/urls.py
from . import views
from django.urls import path


# app name should be there i guess
app_name = 'articles'

urlpatterns = [
    path('',views.list_article,name='list_article'),
    path('article/search/', views.article_search_view, name='search'),
    path('article/create/',views.article_create,name='create'),
    path('articles/detail/<slug:slug>/',views.detail_view,name='detail'),
]

menusite/menusite/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('articles.urls')),
    path('accounts/',include('accounts.urls')),
    path('pantry/recipes/',include('recipes.urls'),)
    # path('pantry/',include('receipe.urls')),
]

menusite/recipes/urls.py
# here we go for different view for the routes
from django.urls import path
from .views import recipe_create_view,recipe_detail_view,recipe_list_view,recipe_update_view,recipe_detail_hx_view


# declaring the app name
app_name = 'recipes'


urlpatterns = [
    path('',recipe_list_view,name='list'),
    path('create/',recipe_create_view,name='create'),
    path('hx/<int:id>/',recipe_detail_hx_view,name='hx-detail'),
    path('<int:id>/edit/',recipe_update_view,name='update'),
    path('<int:id>/',recipe_detail_view,name='detail'),
]

menusite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/htmx.org@2.0.4"></script>
    <title>
        {% block title %}
        
        {% endblock title %}
    </title>
</head>
<body>
    <form action="{% url 'articles:search' %}" method="GET">
        <input type='text' name='q'>
        <input type='submit' value="search">
    </form>
    {% block content %}
    
    {% endblock content %}
</body>
</html>

menusite/templates/create.html
{% extends "base.html" %}


<{% block title %}
 Create Article
{% endblock title %}



{% block content %}
   <div style="margin-top:30px">
     {% if not created %}
    
    
     <form action="{% url 'articles:create' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <input type="submit" value="submit">
        </div>
     </form>

     {% else %}
     <p>New Article has been created.</p>
     <p>
        <a href="{% url 'articles:detail' object.slug %}">You can go here to read the article.</a>
        or
        <a href="{% url 'articles:list_article'%}">read all the articles here.</a>
     </p>
    {% endif %}
   </div>
{% endblock content %}

menusite/templates/detail.html
{% extends "base.html" %}

{% block title %}
    {{ article.title }}
{% endblock title %}


{% block content %}
  <h1>{{ article.title }}</h1>
  <p style="color:blue">Article written by - {{ article.user }}</p>
  <p>
     {{ article.content }}
  </p>
{% endblock content %}

menusite/templates/list.html
{% extends "base.html" %}

{% block title %}
  
    List Article

{% endblock title %}

{% block content %}

   <p>
    <a href="{% url 'articles:create' %}">Create new article here</a>
   </p>

   {% for article in  articles %}
       <ul>
         <li><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></li>
       </ul>
   {% endfor %}

{% endblock content %}

menusite/templates/search.html
{% extends "base.html" %}

{% block title %}
search
{% endblock title %}


{% block content %}
  <h1>Related article about the search</h1>
  {% if object %}
     {% for article in object %}
        <ul>
            <li><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></li>
        </ul>
     {% endfor %}
  {% else %}
    <p>No related data found</p>
  {% endif %}
{% endblock content %}